# Generated by Django 4.0.5 on 2022-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
    ]
